version: "3.0"
services:
    web:
        build: ./magento2-apache-php
        container_name: web
        volumes:
          - ./magento2:/var/www/html
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        links:
          - mysql
          - redis
    mysql:
        image: mariadb
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8080:80"
        links:
          - mysql:db
        depends_on:
          - mysql
    #add Redis service and connect to internal data volume
    redis:
        image: redis:latest
        restart: always
        container_name: redis
        volumes:
          - redis-data:/data
volumes:
    db-data:
        external: false
    #add internal data volume so that data persists
    redis-data:
        external: false